### ISSUE TITLE
Please consider to add interfaces and data types (basic type and struct) into bookmark tree

### ISSUE THREAD

**Issue by Xiliusha** [KhronosGroup/Vulkan-Web-Registry#9]
This is the current Vulkan Specification pdf bookmark tree:
I can't have a overview to all interfaces or data types.
![image](https://user-images.githubusercontent.com/40131112/106410430-cbee1700-647d-11eb-8d0f-270e43061543.png)

Consider to add more bookmarks, for example:
This is my personal bookmarks append to default bookmark
![image](https://user-images.githubusercontent.com/40131112/106410279-74e84200-647d-11eb-9c5f-94394d3aee06.png)

**Comment by oddhack** [comment]
This would make the bookmark index in the PDF viewer go from about 7 screens worth of information to about 40 (depending on window size I suppose), and make the main index in the spec go from 9 pages to about 50 (or equivalently, from about 350 bookmarks to about 2100), since the bookmarks and index are driven off the same asciidoctor markup in the spec source. It would also require a significant global change in spec markup. So I don't think this is something we want to do - but it might be relatively straightforward for you to do it yourself, using a tool like [pdftk, as suggested here](https://stackoverflow.com/questions/30304718/create-bookmarks-into-a-pdf-file-via-command-line).

**Comment by oddhack** [comment]
As a possible alternative, the chunked HTML spec's built-in searchbox might be helpful.
